import bcrypt from 'bcryptjs';

const data = {

  users: [
    {
    name: 'Hafiz',
    email: 'admin@admin.com',
    password: bcrypt.hashSync('1234', 8),
    isAdmin: true,
    isSponsor: true,
    isVendor: true,
    },
    {
      name: 'Swatt',
      email: 'user@user.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
      isSponsor: true,
      isVendor: false,
    },
    {
        name: 'lola',
        email: 'lola@user.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: false,
        isSponsor: false,
        isVendor: true,
    },
  ],

  logo: 
  {
      image: '/images/0001.jpg',
      name: 'Kai Vida Logo'
  },
  products: [
    {
     name: 'Beef and Bean Chili',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 },
 {
     name: 'Cheesy Burger',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 },
 {
     name: 'Chicken Dumplings',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 0,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 },
 {
     name: 'Chicken Burrito Bowls',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 }, 
 {
     name: ' Veggie Bowls',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high  quality product',
 },
 {
     name: 'Noodle Cabbage bowl ',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 },
 {
     name: 'Cous Cous Bowls',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 },
 {
     name: 'Three Bean Chilli',
     category: 'shirts',
     image: '/images/d1.jpeg',
     price: 120,
     countInStock: 10,
     brand: 'Nike',
     rating: 4.5,
     numReviews: 10,
     description: 'high quality product',
 },
],
  };
  export default data;
   