export const USER_SREGISTER_REQUEST = 'USER_SREGISTER_REQUEST';
export const USER_SREGISTER_SUCCESS = 'USER_SREGISTER_SUCCESS';
export const USER_SREGISTER_FAIL = 'USER_SREGISTER_FAIL';

export const USER_VREGISTER_REQUEST = 'USER_VREGISTER_REQUEST';
export const USER_VREGISTER_SUCCESS = 'USER_VREGISTER_SUCCESS';
export const USER_VREGISTER_FAIL = 'USER_VREGISTER_FAIL';

export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_SIGNOUT = 'USER_SIGNOUT';